// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace test2.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int IdCategory { get; set; }

    public int IdManufacturer { get; set; }

    public int IdSupplier { get; set; }

    public int IdUnit { get; set; }

    public decimal Price { get; set; }

    public int Quantity { get; set; }

    public int Discount { get; set; }

    public string PhotoPath { get; set; }

    public virtual Category IdCategoryNavigation { get; set; }

    public virtual Manufacturer IdManufacturerNavigation { get; set; }

    public virtual Supplier IdSupplierNavigation { get; set; }

    public virtual Unit IdUnitNavigation { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}