// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace test2.Models;

public partial class User
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int IdRole { get; set; }

    public virtual Role IdRoleNavigation { get; set; }
}